### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException: getParameters failed (empty parameters)

### ISSUE THREAD

**Issue by azzadpandit1** [AuroScholar/Auro_ProctoringSDK_Library#11]
Fatal Exception: java.lang.RuntimeException: getParameters failed (empty parameters)
       at android.hardware.Camera.native_getParameters(Camera.java)
       at android.hardware.Camera.getParameters(Camera.java:2109)
       at com.example.auroproctoringsdk.ProctoringSDK.captureImage$lambda$1(ProctoringSDK.kt:254)
       at com.example.auroproctoringsdk.ProctoringSDK.$r8$lambda$PruFxecpRciZiPikv5OkyVJG1QI()
       at com.example.auroproctoringsdk.ProctoringSDK$$ExternalSyntheticLambda0.onPreviewFrame(:2)
       at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1183)
       at android.os.Handler.dispatchMessage(Handler.java:106)

**Comment by azzadpandit1** [comment]
Fixed
